
CREATE DATABASE ATENDIMENTO_CLINICA;
GO

USE ATENDIMENTO_CLINICA;
GO

CREATE TABLE PET (
	idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
	racaPet VARCHAR(20),
	tipoPet VARCHAR(20)
);
GO

CREATE TABLE VETERINARIO (
	idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	nomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE CLINICA (
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	nomeCliente VARCHAR(20)
);
GO
