
CREATE DATABASE ATENDIMENTO
GO

USE ATENDIMENTO
GO

CREATE TABLE MARCA (
	idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(20) NOT NULL
);
GO

CREATE TABLE MODELO (
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeModelo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE VEICULO (
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
	dataVeiculo CHAR(4) NOT NULL
);
GO

CREATE TABLE ALUGUEL (
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	nomeCliente VARCHAR(20) NOT NULL
);
GO

