
CREATE DATABASE PLATAFORMA;
GO

USE PLATAFORMA
GO

CREATE TABLE PERMISSIONAMENTO (
	idPermissao TINYINT PRIMARY KEY IDENTITY(1,1),
	permissao CHAR(5)
);
GO

CREATE TABLE ALBUM (
	idAlbum TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeAlbum VARCHAR(20)
);
GO

CREATE TABLE PLATAFORMA (
	idPlataforma TINYINT PRIMARY KEY IDENTITY(1,1),
	idAlbum TINYINT FOREIGN KEY REFERENCES ALBUM(idAlbum)
);
GO

CREATE TABLE ESTILO (
	idEstilo TINYINT PRIMARY KEY IDENTITY(1,1),
	idAlbum TINYINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	nomeEstilo VARCHAR(20)
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPermissao TINYINT FOREIGN KEY REFERENCES PERMISSIONAMENTO(idPermissao),
	idPlataforma TINYINT FOREIGN KEY REFERENCES PLATAFORMA(idPlataforma),
	nome VARCHAR(20),
	senha VARCHAR(20),
	email VARCHAR(20)
);
GO
